### ISSUE TITLE
麻烦问下 最后一个获取首页直播内容的怎么没有了

### ISSUE THREAD

**Issue by HotBitmapGG** [WhiteBlue/bilibili-go#12]
昨天白天调用还是正常的，晚上就不能访问了，已经删除了嘛？

**Comment by WhiteBlue** [comment]
重构了一波代码，那个接口之前以为没多大用，所以去掉了

**Comment by HotBitmapGG** [comment]
别啊,我现在做个高仿的安卓端，需要这些直播内容，之前我是自己抓包抓的B站Api，但是需要AppKey，而且调用次数过多 就会被封了，然后就发现你的这个Api了，但是你居然删除了，直播的那个还是挺有用的，能恢复下嘛？

**Comment by HotBitmapGG** [comment]
希望能恢复下，真心感谢，

**Comment by WhiteBlue** [comment]
近期恢复吧....

**Comment by WhiteBlue** [comment]
已修复
