### ISSUE TITLE
搜索请求报400的参数错误

### ISSUE THREAD

**Issue by 879479119** [WhiteBlue/bilibili-go#14]
因为使用的是react native，没有原生的表单    所以是手动生成的表单发送数据，服务器返回参数错误
我是头设置错了吗？
![issue516](https://cloud.githubusercontent.com/assets/12726506/18084847/5bbddbec-6edb-11e6-8c3a-6645619e78c8.png)
![is](https://cloud.githubusercontent.com/assets/12726506/18084928/9cff1dfa-6edb-11e6-8652-8322865a8f6d.png)
返回值{"code":"PARAM_ERROR","message":""}

**Comment by WhiteBlue** [comment]
使用`x-www-form-urlencoded`试下

**Comment by 879479119** [comment]
嗯    刚刚解决了这个问题  使用`x-www-form-urlencoded`就好了，传参数也是直接用的字符串  我多此一举了。     `search`这个接口如何选择子分类筛选呢

**Comment by WhiteBlue** [comment]
目前还没做。。。之后补吧
