### ISSUE TITLE
新番推荐接口返回的spid的问题

### ISSUE THREAD

**Issue by HotBitmapGG** [WhiteBlue/bilibili-go#15]
这个接口返回的新番列表里，所有的spid都是0 。

**Comment by HotBitmapGG** [comment]
抱歉，搞错，是5. 番剧更新列表这个接口，我看了下，所有的spid都是0，就不能根据spid去查询详情数据了

**Comment by WhiteBlue** [comment]
这个毫无办法.... B站API返回的本身就是`0`

**Comment by HotBitmapGG** [comment]
@WhiteBlue 好吧 ，麻烦了
