### ISSUE TITLE
赞扬一下，不过很奇怪的是search搜不到东西……

### ISSUE THREAD

**Issue by superfashi** [WhiteBlue/bilibili-go#16]
额，先不吐槽函数的实现方法……
Search 接口没有办法搜到东西，返回的 list 为空，非常奇怪，因为就算我改 Post 参数也不行，但是接口却是正确的……

**Comment by WhiteBlue** [comment]
函数实现....
如果说接口的话因为有的项目在用所以不好改动  

Search的问题参考这里 [ issue14 ](https://github.com/WhiteBlue/bilibili-go/issues/14)
