### ISSUE TITLE
视频地址解析出来的视频链接不对

### ISSUE THREAD

**Issue by nicolasiJasica** [WhiteBlue/bilibili-go#2]
大侠 ：
”4. 视频地址解析“解析出来的视频链接跟视频对不上
咋回事儿呢?

**Comment by WhiteBlue** [comment]
这里取得播放地址要用`cid`，`cid`可以在之前的接口里拿到，(avXXXX指的是aid)

**Comment by nicolasiJasica** [comment]
多谢，之前误把 aid当成了cid，现在可以了。
另外顺便问一下，我现在拿到的视频播放地址，是播放的B站的服务器上的还是另外提供的服务器上的呀？

**Comment by WhiteBlue** [comment]
B站的视频源大多是第三方吧..

**Comment by nicolasiJasica** [comment]
好，万分感谢
