### ISSUE TITLE
接口返回都是404

### ISSUE THREAD

**Issue by Juniorchen2012** [WhiteBlue/bilibili-go#26]
接口返回都是404

**Comment by WhiteBlue** [comment]
Daocloud的免费容器不给用了来着....还在找新的

**Comment by alexykuan** [comment]
大神加油啊~  T V T ，还有大神有b站手机视频源接口吗？

**Comment by DIYgod** [comment]
我在阿里云搭了一个：https://api.prprpr.me/bilibili/

**Comment by WhiteBlue** [comment]
@alexykuan 嗯有空看看手机端的接口，虽然感觉区别大概不大

**Comment by HotBitmapGG** [comment]
加油啊

**Comment by HotBitmapGG** [comment]
@WhiteBlue 有个问题问下，现在b站的sign算法是不是改了 我用之前的算法算sign总是说不对

**Comment by WhiteBlue** [comment]
@HotBitmapGG 没改吧，一般提示sign有问题大半是参数不够
