### ISSUE TITLE
你还有其它什么二次元app或网站的接口吗？？？

### ISSUE THREAD

**Issue by noear** [WhiteBlue/bilibili-go#8]
我都想为它开发SiteD插件：）

**Comment by WhiteBlue** [comment]
这个API本意其实是想给js做跨域调用.....只是对B站API加密做了层封装罢了....API汇总可以看这个项目`https://github.com/jabbany/dhufufu`

**Comment by noear** [comment]
SiteD插件，就是采用xml+js来实现的；讲起来像一个xhtml（有js有xml）；
它可以对接一些已有的接口数据；或者解析网页的html（或其它格式）。

有没有兴趣也开发个SiteD插件：）

**Comment by noear** [comment]
多多猫app可以支持：漫画，轻小说，动画，周边，图片，资讯....这些类型的插件（二次元主题的）。

**Comment by WhiteBlue** [comment]
坑太多了orz.....不过后续可能的话会看看这个API有没有什么能扩展的
