### ISSUE TITLE
强烈希望你能为多多猫app开发些插件！！！（1个插件约等于1个跨平台的APP）

### ISSUE THREAD

**Issue by noear** [WhiteBlue/bilibili-go#9]
这是我前天花2到3小时开发的Bilibili插件：
http://sited.noear.org/addin/site3007.sited.xml

**Comment by noear** [comment]
这是插件开发者中心：http://sited.noear.org/dev/

**Comment by MoeGakuen** [comment]
就你话多

**Comment by noear** [comment]
因为我正在跟一些人一起玩；多多猫插件，是个开放技术。很多人可以一起玩：）
多有意思。

**Comment by noear** [comment]
它可以直接接入附合数据格式的web api；也可以中转不一样的数据：）
